#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker600)
#pragma config(Sensor, S3,     Ultra,          sensorSONAR)
#pragma config(Sensor, S4,     Ultra2,         sensorSONAR)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     Right,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mLift,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     mIntake,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     mFlag,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     Left,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     mDispenser,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    sCubes,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "FunctionLibrary.c"
task main()
{
	waitForStart();
	int beacon = 0;
	int i = 0;

	//time to find dat beacon
	while(!(i >= 4 && i <= 6) && beacon < 4)
	{
		for(int a = 0; a <100; a++)
		{
			if( a == 0)
			{
				i  = SensorValue[IR];
			}
			else
			{
				int b = SensorValue[IR];
				if(b != i)
				{
					a = 0;
				}
			}
		}
		if(!(beacon == 0 || beacon == 2))
		{
			ForwardWithTime(500,100);
			motor[Left] = 0;
			motor[Right] = 0;
			wait1Msec(1000);
		}
		else if(beacon == 0)
		{
			ForwardWithTime(1388,100);
			motor[Left] = 0;
			motor[Right] = 0;
			wait1Msec(1000);
		}
		else if(beacon == 2)
		{
			ForwardWithTime(1275,100);
			motor[Left] = 0;
			motor[Right] = 0;
			wait1Msec(1000);
		}
		beacon++;
	}

	//time to drop dat cube into dat box
	//motor[Left] =  -100;
	//motor[Right] = 100;
	//wait1Msec(700);
	//motor[Left] = 0;
	//motor[Right] = 0;
	//wait1Msec(1000);

	//ForwardWithTime(1000,100);
	//motor[Left] = 0;
	//motor[Right] = 0;
	//wait1Msec(1000);
	//servo[sCubes] = 255;
	//wait1Msec(500);

	//BackwardWithTime(1000,100);
	//motor[Left] = 0;
	//motor[Right] = 0;
	//wait1Msec(1000);

	////pick where to  go based on beacon #.
	//if(beacon == 1)
	//{
	//	motor[Left] = 100;
	//	motor[Right] = -100;
	//	wait1Msec(1000);
	//	BackwardWithTime(1000,100);
	//	motor[Left] = 100;
	//	motor[Right] = -100;
	//	wait1Msec(500);
	//	ForwardWithTime(1000,100);
	//}
	//else if (beacon == 2)
	//{
	//	motor[Left] = 100;
	//	motor[Right] = -100;
	//	wait1Msec(1500);
	//	BackwardWithTime(1200,100);
	//	motor[Left] = 100;
	//	motor[Right] = -100;
	//	wait1Msec(700);
	//	ForwardWithTime(1000,100);
	//}
	//else if (beacon == 3)
	//{
	//	motor[Left] = 100;
	//	motor[Right] = -100;
	//	wait1Msec(1500);
	//	BackwardWithTime(1200,100);
	//	motor[Left] = 100;
	//	motor[Right] = -100;
	//	wait1Msec(700);
	//	ForwardWithTime(1000,100);
	//}
	//else if (beacon == 4)
	//{
	//	motor[Left] = -100;
	//	motor[Right] = 100;
	//	wait1Msec(1000);
	//	BackwardWithTime(1000,100);
	//	motor[Left] = -100;
	//	motor[Right] = 100;
	//	wait1Msec(500);
	//	ForwardWithTime(1000,100);
	//}

}
