#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     Ultra,          sensorSONAR)
#pragma config(Sensor, S3,     Ultra2,         sensorSONAR)
#pragma config(Sensor, S4,     IR,             sensorHiTechnicIRSeeker600)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     Right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     mFlag,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     mLift,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     mWinch1,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     mWinch2,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    sCubes,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "FunctionLibrary.c"
#include "JoystickDriver.c"

task main()
{
	//ForwardWithTime(2100,70);
	//waitForStart();
	nMotorEncoder[mLift] = 0;
	while(nMotorEncoder[mLift] < 2800)
	{
		motor[mLift] = 50;
	}

	motor[mLift] = 0;
	ForwardWithTime(2600,70);
	wait1Msec(1000);
	servo[sCubes] = 0;
	wait1Msec(200);
	servo[sCubes] = 255;
	wait1Msec(200);
	servo[sCubes] = 127;
  wait1Msec(500);

	/*
  BackwardWithTime(1350,70);
	wait1Msec(500);
	motor[Left] = 100;
	motor[Right] = -100;
	wait1Msec(500);
  motor[Right] = 100;
  motor[Left] = -100;
  wait1Msec(500);
  ForwardWithTime(3400,100);
  wait1Msec(500);
  motor[Right] = 100;
  motor[Left] = -100;
  wait1Msec(500);

	while(nMotorEncoder[mLift] > 0)
	{
		motor[mLift] = -50;
	}
  motor[mLift] = 0;
  wait1Msec(700);
  BackwardWithTime(1070,100);
  wait1Msec(500);
*/
 }
