#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     mR1,           tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     mR2,           tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     mL1,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     mL2,           tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define IR_REGION 5
void mL(int power) {
	motor[mL1]=motor[mL2]=power;
}

void mR(int power) {
	motor[mR1]=motor[mR2]=power;
	}

task main()
{


mL(100);
mR(100);
while(sensorvalue[IR] != IR_REGION){}
mL(0);
mR(0);
wait10Msec(100);
mL(-100);
mR(100);
wait10Msec(50);
mL(0);
mR(0);


}
