#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Ultra,          sensorSONAR)
#pragma config(Sensor, S3,     Ultra2,         sensorSONAR)
#pragma config(Sensor, S4,     IR,             sensorHiTechnicIRSeeker600)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     mLeft,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     mLeft2,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     mRight,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     mRight2,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
	while(true)
	{
		getJoystickSettings(joystick);
		if(abs(joystick.joy1_y2)>10) //prevents idle movement from small values
		{
			motor[mLeft] = joystick.joy1_y2;
			motor[mLeft2] = joystick.joy1_y2;
		}
		else
		{
			motor[mLeft] = 0; //stops movement of the left side
			motor[mLeft2] = 0;
		}

		if(abs(joystick.joy1_y1)>10)
		{
			motor[mRight] = joystick.joy1_y1;
			motor[mRight2] = joystick.joy1_y1;
		}
		else
		{
			motor[mRight] = 0; //stops movement of the right side
			motor[mRight2] = 0;
		}
	}
}
