#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     IR,             sensorHiTechnicIRSeeker600)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     Right,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mLift,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     mIntake,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     mFlag,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     Left,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     mDispenser,    tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "FunctionLibrary.c"
#include "JoystickDriver.c"
#define right -1
#define left 1

task main()
{
	waitForStart();
	 motor[Right] = 100;
	 motor[Left] = 100;
	 wait1Msec(2300);
	 motor[Left] = 0;
	 motor[Right] = 0;
	 nMotorEncoder[mLift] = 0;
	while(nMotorEncoder[mLift] < 3800)
	{
		motor[mLift] = 50;
	}

	motor[mLift] = 0;
	motor[Right] = 100;
	motor[Left] = 100;
	wait1Msec(1000);
	motor[mDispenser] = 50;
	wait1Msec(500);
	motor[mDispenser] = -50;
	wait1Msec(500);
	motor[mDispenser] = 0;
	wait1Msec(100);

//	waitForStart();
	//wait1Msec(20000);
//  motor[mLift] = 100;
//  wait1Msec(700);
//  motor[mLift] = 0;
//  wait1Msec(200);
//  motor[Right] = 100;
//  motor[Left] = 100;
//  wait1Msec(2500);
// motor[Right] = 0;
//  motor[Left] = 0;
  //motor[Right] = 100;
  //motor[Left] = -100;
  //wait1Msec(500);
  //motor[Right] = 0;
  //motor[Left] = 0;
  //wait1Msec(200);
}
