#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Ultra,          sensorSONAR)
#pragma config(Sensor, S3,     Ultra2,         sensorSONAR)
#pragma config(Sensor, S4,     IR,             sensorHiTechnicIRSeeker600)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     mLift2,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     mLift1,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     mFlag,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     Left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     mWrist,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    AutoHook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    sHook,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Include file to handle the messages from the field control system
// This is how the robot responds to the drivers.
#include "JoystickDriver.c"
// the max motor value
#define max 100
// the min motor value
#define min 0
// the maximum lift power
#define lift_max 100
// the minimum lift power
#define lift_min 0
// the threshold of when the lift is considered down
#define thresh 4700

// whether sniper mode is currently enabled
// Sniper mode allows the drivers to slow down the robot for more precise movements.
bool sniper = false;
// whether the slide limit function is enabled
bool limit = false;
// whether the slide is all the way down
bool bottom = false;
// whether slide is completely extended
bool extended = false;
// whether the slide toggle button is currently down
bool clicked = false;
// whether the slide toggle button was previously down
// This is used to prevent double-triggering the toggle function.
bool prevClicked = false;

/*------------------------------------------------|
|Motor A1 is Right; Motor A2 is mDispenser.				|
|Motor C1 is mLift; Motor C2 is mWrist.						|
|Motor B1 is mHinge;Motor B2 is Left.							|
|servo1 is sHook; servo2 is AutoDispenser.				|
|Motors run on a scale of -100(max backwards) to  |
|100 (max forwards), with no power being 0.				|
|Servos run on a scale of 0 (max backwards) to 		|
|256(max forwards), with 127 being no power.			|
|-------------------------------------------------*/


void sniperCheck() //checks to see if the robot should go in "sniper"/slow mode.
{
	if(joy1Btn(5))
	{
		sniper = true;
	}
	else
	{sniper = false;}
}

void drive() //moving method
{
	if(!sniper)
	{
		if(abs(joystick.joy1_y2)>10) //prevents idle movement from small values
		{
			if(joystick.joy1_y2>0)
			{
				motor[Left] = pow(joystick.joy1_y2, 2)/100;
			}
			else
			{
				motor[Left] = -pow(joystick.joy1_y2, 2)/100;
			}
		}
		else
		{
			motor[Left] = 0; //stops movement of the left side
		}

		if(abs(joystick.joy1_y1)>10)
		{
			if(joystick.joy1_y1>0)
			{
				motor[Right] = pow(joystick.joy1_y1, 2)/100;
			}
			else
			{
				motor[Right] = -pow(joystick.joy1_y1, 2)/100;
			}
		}
		else
		{
			motor[Right] = 0; //stops movement of the right side
		}
	}
	else
	{
		if(abs(joystick.joy1_y2)>10) //prevents idle movement from small values
		{
			if(joystick.joy1_y2>0)
			{
				motor[Left] = pow(joystick.joy1_y2, 2)/400;
			}
			else
			{
				motor[Left] = -pow(joystick.joy1_y2, 2)/400;
			}
		}
		else
		{
			motor[Left] = 0;
		}

		if(abs(joystick.joy1_y1)>10)
		{
			if(joystick.joy1_y1>0)
			{
				motor[Right] = pow(joystick.joy1_y1, 2)/400;
			}
			else
			{
				motor[Right] = -pow(joystick.joy1_y1, 2)/400;
			}
		}
		else
		{
			motor[Right] = 0; //stops movement of the right side
		}
	}


}


// Handle the slide lift controls
// Automatically switches between the lower and upper level motors by
// using the motor encoder values.
void newLift()
{
	if(!clicked) // if on automatic mode for the slide lift
	{
		//motor[motorA] = 0;
	servo[AutoHook] = 0;
		if(nMotorEncoder[mLift1] >= thresh)
		{
			extended = true; // update the flags to show that the lower level is fully extended
			bottom = false; // update the flags to show that the lower level is fully extended
		}
		else if(nMotorEncoder[mLift1] <= 200) // otherwise, if the lower level is fully lowered
		{
			bottom = true; // update the flags to show that the lower level is fully lowered
			extended = false; // update the flags to show that the lower level is fully lowered
		}
		if(joystick.joy2_y1 > 25)
		{
			if(bottom) // if the slide is on the bottom
			{
				motor[mLift1] = joystick.joy2_y1; // raise the lower level motor
				motor[mLift2] = 0; // halt the upper level motor
			}
			else if(extended) // otherwise, if the slide is extended
			{
				motor[mLift2] = joystick.joy2_y1; // raise the upper level motor
				motor[mLift1] = 0; // halt the lower level motor
			}
		}
		else if(joystick.joy2_y1 < 25)
		{
			if(bottom) // if the slide is on the bottom
			{
				motor[mLift1] = 0; // halt the lower level motor
				motor[mLift2] = joystick.joy2_y1; // lower the upper level motor
			}
			else // otherwise, if the slide is extended
			{
				motor[mLift2] = 0; // halt the upper level motor
				motor[mLift1] = joystick.joy2_y1; // lower the lower level motor
			}
		}
	}
	else
	{
		//motor[motorA] = 100;
		servo[AutoHook] = 100;
		if(joystick.joy2_TopHat == 0)
		{
			motor[mLift1] = 100; // raise the lower level motor
		}
		else if(joystick.joy2_TopHat == 4) // if the bottom button of the pad is pressed
		{
			motor[mLift1] = -100; // lower the lower level motor
		}
		else if(joy2Btn(5)) // if the button marked '5' is pressed
		{
			motor[mLift2] = 100; // raise the upper level motor
		}
		else if(joy2Btn(7)) // if the button marked '7' is pressed
		{
			motor[mLift2] = -100; // lower the upper level motor
		}
		else
		{
			motor[mLift2] = 0; // halt the upper level motor
			motor[mLift1] = 0; // halt the lower level motor
		}
	}
}

// Handle the button to toggle manual/automatic mode on the slide lift
void isClicked()
{
	if(joy2Btn(11)) // if the toggle button is currently pressed
	{
		if(!prevClicked) // if the toggle button was just now pressed (avoids double-toggling)
		{
			clicked = !clicked; // toggle the manual override flag
			prevClicked = true; // record the the button is no longer freshly pressed
		}

	}
	else // otherwise, if the button is not pressed
	{
		prevClicked = false; // reset the flag for whether the button is freshly pressed
	}
}

// Handle the hook for raising the robot
void autoHook()
{
	if(joy1Btn(4)) // if the button marked '4' is pressed
	{
		servo[AutoHook] -= 5; // turn the hook counterclockwise
	}
	if(joy1Btn(2)) // if the button marked '5' is pressed
	{
		servo[AutoHook] += 5; // turn the hook clockwise
	}
}

// Moves the wrist part of the dispenser up and down
void wrist()
{
	if(abs(joystick.joy2_y2) > 10) // if the joystick is pushed up
	{
		motor[mWrist] = joystick.joy2_y2/4; // rotate the wrist up
	}
	else // otherwise, if the joystick is not pushed up
	{
		motor[mWrist] = 0; // halt the wrist motor
	}
}

// flag method
void flag()
{
	if(!sniper) // if sniper mode is not enabled
	{
		if(joystick.joy2_TopHat == 2)
			motor[mFlag]= 100; //moves flag attachment clockwise
		else if(joystick.joy2_TopHat == 6 )
			motor[mFlag]= -100; //moves flag attachment counterclockwise
		else
			motor[mFlag] = 0; //stops moving flag attachment
	}
	else // otherwise, if sniper mode is enabled
	{
		if(joystick.joy2_TopHat == 2)
			motor[mFlag]= 50; //moves flag attachment clockwise
		else if(joystick.joy2_TopHat == 6 )
			motor[mFlag]= -50; //moves flag attachment counterclockwise
		else
			motor[mFlag] = 0; //stops moving flag attachment
	}
}
void liftLimit() // sets a limit for the lift; this prevents it from going past that point.
{
	if(joy2Btn(10))
	{
		limit = true;
		nMotorEncoder[mLift1] = 0;
	}
	if(limit)
	{
		if(nMotorEncoder[mLift1] < 0)
		{
			while(nMotorEncoder[mLift1] < 0)
			{
				motor[mLift1] = 90;
			}
			motor[mLift1] = 0;
		}
		if (joy2Btn(9))
		{
			limit = false;
		}
	}
}

void hook() //controls the hook's side-to-side movement.
{
	if(joy2Btn(4))
	{
		servo[sHook] += 5;
	}
	else if(joy2Btn(2))
	{
		servo[sHook] -= 5;
	}
}

task main()
{
	nMotorEncoder[mLift1] = 0;

	servo[sHook] = 0;
	servo[AutoHook] = 0;
	motor[Left] = 0;
	motor[Right] = 0;
	motor[mLift1] = 0;
	motor[mLift2] = 0;
	motor[mFlag] = 0;
	motor[mWrist] = 0;

	while(true)
	{
		getJoystickSettings(joystick);  // Update Buttons and Joysticks
		if(!bDisconnected)//makes  sure robot is still connected to Samantha
		{
			sniperCheck();
			drive();
			flag();
			newLift();
			isClicked();
			liftLimit();
			hook();
			wrist();
			autoHook();
			//all of the above code runs the methods that control all the motorized parts of our robot.
			wait1Msec(10); //a wait to ensure that multiple signals do not stack and to prevent lag.
		}
		else
		{
			motor[Left] = 0;
			motor[Right] = 0;
			motor[mLift1] = 0;
			motor[mLift2] = 0;
			motor[mFlag] = 0;
			motor[mWrist] = 0;
			//sets everything to stop if bluetooth  is disconnected.
		}
	}
}
