#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Ultra,          sensorSONAR)
#pragma config(Sensor, S3,     Ultra2,         sensorSONAR)
#pragma config(Sensor, S4,     IR,             sensorHiTechnicIRSeeker600)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     mLift2,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     mLift1,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     mFlag,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     Left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     mWrist,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    AutoHook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    sHook,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define left 1
#define right -1

// whether the user has finished selecting a delay time
bool timeSelected = false;
// whether the robot will wait for the FCS to start (disable when testing)
bool startSelected = false;
// whether the user has selected to delay at the beginning of autonomous
bool waitSelected = true;
// how many seconds to delay before starting autonomous (used for coordinating with
// other teams)
int waitTime = 0;
// the message used by the wait prompt
string wait = "Yes";
//holds which  autonomous program we will be running
int programCounter = 1;
//holds the  maximum amount of autonomous programs we can run
int max = 5;
//holds which beacon the robot is at
int beacon = 0;
//holds the IR sensor value
int i = 0;


// standard library for talking to Samantha FCS
#include "JoystickDriver.c"
// our team-built function library
#include "FunctionLibrary.c"
//our team-built Autonomous library
#include "AutonomousLibrary_NorCal.c"

task main()
{
	selectTime();
	startSelect();
	if(waitSelected){waitForStart();}
	wait1Msec(waitTime*1000);
	Forward(5000, 100);
}
