#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Ultra,          sensorSONAR)
#pragma config(Sensor, S3,     Ultra2,         sensorSONAR)
#pragma config(Sensor, S4,     IR,             sensorHiTechnicIRSeeker600)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     mLift2,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     mLift1,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     mFlag,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     Left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     mWrist,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    AutoHook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    sHook,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//values we use in our turn mmethod to determine which direction we turn.
#define left 1
#define right -1

//holds whether we have decided the time we will wait or not.
bool timeSelected = false;
//holds whether we have selected to waitForStart().
bool startSelected = false;
//holds whether we have chosen to have a wait in our program.
bool waitSelected = true;
// the wait time for the program.
int waitTime = 0;
//the beacon the robot will travel to.
int beacon = 1;
//The message used by the wait method.
string wait = "Yes";


#include "JoystickDriver.c"
#include "FunctionLibrary.c"

task main()
{
	beacon = picker(); //assigns the beacon we want to go to to this value.
	selectTime(); //do we want to wait before we start the program?
	startSelect(); //do we want to waitForStart()?
	if(waitSelected)
	{
		waitForStart(); //waits for a start message.
	}
	wait1Msec(1000*waitTime); //the amount of time we wait before starting the program.

	if(beacon == 1) //going to the first beacon
	{
		//the distance to get to the first beacon
		ModForward(2400,35);
		motor[Right] = 0;
		motor[Left] = 0;
		wait1Msec(1000);
	}
	else if(beacon == 2) //going to the second beacon
	{
		//the distance to get to the second beacon
		ModForward(3500,35);
		motor[Right] = 0;
		motor[Left] = 0;
		wait1Msec(1000);
	}
	else if(beacon == 3) //going to the third beacon
	{
		//the distance to get to the third beacon
		ModForward(5400,35);
		motor[Right] = 0;
		motor[Left] = 0;
		wait1Msec(1000);
	}
	else if(beacon == 4) //going to the fourth beacon
	{
		//the distance to get to the fourth beacon
		ModForward(6400,35);
		motor[Right] = 0;
		motor[Left] = 0;
		wait1Msec(1000);
	}

	//code that runs after  we stop in front of a beacon.
	servo[AutoHook] = 255;	//dispenses the cube
	wait1Msec(900);
	servo[AutoHook] = 0;
	wait1Msec(1000);

	//pick where to  go based on beacon #.
	//if the robot is at rings 1 or 4, it turns, goes back, then turns to face the ramp.
	//if the robots is at rings 2 or 3, it goes backwards, turns, goes backwards again, and then turns to face the ramp.
	if(beacon == 1) //beacon was on first box
	{
		//goes backwards from the box
		ModBackward(1760,50);
		motor[Right] = 0;
		motor[Left] = 0;
		wait1Msec(500);

		//turns to be parallel to the ramp
		ModTurn(1840, 100, right);
		motor[Right] = 0;
		motor[Left] = 0;
		wait1Msec(500);

		//goes backwards and towards the ramp
		ModBackward(4000,50);
		motor[Right] = 0;
		motor[Left] = 0;
		wait1Msec(500);

		//turns towards the ramp
		ModTurn(2700, 100, right);
		motor[Right] = 0;
		motor[Left] = 0;
		wait1Msec(500);

		//goes onto the ramp
		ModBackward(4500,100);
	}
	else if (beacon == 2) //beacon was on second box
	{
		//goes backwards from the box
		ModBackward(2900,50);
		motor[Right] = 0;
		motor[Left] = 0;
		wait1Msec(500);

		//turns to be parallel to the ramp
		ModTurn(1840, 100, right);
		motor[Right] = 0;
		motor[Left] = 0;
		wait1Msec(500);

		//goes backwards and towards the ramp
		ModBackward(4000,50);
		motor[Right] = 0;
		motor[Left] = 0;
		wait1Msec(500);

		//turns towards the ramp
		ModTurn(2700, 100, right);
		motor[Right] = 0;
		motor[Left] = 0;
		wait1Msec(500);

		//goes onto the ramp
		ModBackward(4500,100);
	}
	else if (beacon == 3) //beacon was on third box
	{
		//goes forward from the box
		ModForward(2700,50);
		motor[Right] = 0;
		motor[Left] = 0;
		wait1Msec(500);

		//turns to be parallel to the ramp
		ModTurn(2040, 100, right);
		motor[Right] = 0;
		motor[Left] = 0;
		wait1Msec(500);

		//goes backwards and towards the ramp
		ModBackward(4000,50);
		motor[Right] = 0;
		motor[Left] = 0;
		wait1Msec(500);

		//turns towards the ramp
		ModTurn(2700,100,left);
		motor[Right] = 0;
		motor[Left] = 0;
		wait1Msec(500);

		//goes onto the ramp
		ModBackward(4500,80);
	}
	else if (beacon == 4) //beacon was on fourth ring
	{
		//goes forward from the box
		ModForward(1560,50);
		motor[Right] = 0;
		motor[Left] = 0;
		wait1Msec(500);

		//turns to be parallel to the ramp
		ModTurn(1940, 100, right);
		motor[Right] = 0;
		motor[Left] = 0;
		wait1Msec(500);

		//goes backwards and towards the ramp
		ModBackward(4000,50);
		motor[Right] = 0;
		motor[Left] = 0;
		wait1Msec(500);

		//turns towards the ramp
		ModTurn(2700,100,left);
		motor[Right] = 0;
		motor[Left] = 0;
		wait1Msec(500);

		//goes onto the ramp
		ModBackward(4500,100);
	}
}
