#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

while(true){
int x=sensorValue[IR];
nxtDisplayString(2,"%2d",x);


}

}
