#pragma config(Motor,  motorA,          mCAT,          tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          mL,            tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          mR,            tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
This is a program for mohair's robot.
Mohair's "Bat Mobeile" for the outreach places that we go to.
This program will look for bluetooth signals coming fromm 2 nxt bricks
This is the reveiving program for the "Master, Slave" setup
it will allow us to have 1 nxt brick contolling the motors getting signals of what motors to move from another nxt
This program will use the left right and enter button of 1 of the nxt's to control 2 motors

*/
task main()
{
	/*
	Here just for syntax refrence (ignore)

	motor[mL]=100;
	motor[mR]=100;
	while (true) {}
	while (nNxtButtonPressed!=kRightButton) {}
	motor[mR]=-100;
	int x=0;

	while (nNxtButtonPressed=kRightButton) {}
	x++;
	(nxtDisplayString(3, "%d", x);

	*/
int x=0;    //Ths line sets the variable x to 0 allowing us for cetain dislpay properties
int xx=0;   // This allows another variale to set to 0 for certain parts with the reciving program
while(true)  //Just a while loop that makes sure the program runs indefianatly
{
eraseDisplay ();  //erases the display at the beining of the program to clear
xx = message;     //this sets our variable to be able to reseave messages from the "Master Nxt" devise
    if (xx==1)    //If the varibable for the messages is equal to 1 witch is the motion for the movment of right
    	{
      x++;                                 //Adds +1 to display everytime right button is pressed
					nxtDisplayString (3, "%d", x);
			motor[mL]=100;                       //robot turns right when right button is pressed
			motor[mR]=-100;
       wait1Msec(1000);                     //waits so it doesn bug up
       motor[mL] = 0;
       motor[mR] = 0;
       wait1Msec(1000);
		}

		if (xx==2)                             //If the variable equals 2 it will move left
			{
		  x--;                                 //Subtracts -1 to display everytime left button is pressed
			nxtDisplayString (3, "%d", x);
			motor[mL]=-100;                      //robot turns left with left button is pressed
			motor[mR]=100;
       wait1Msec(1000);                   // waits so it doesnt bug up - no
       motor[mL] = 0;
       motor[mR] = 0;
       wait1Msec(1000);
		}

		if (xx==3)                            //If the varibable equals 3 ( if the ceneter/orange/enter button is pressed) it moves forward
			{
		  motor[mL]=100;                      //robot moves forward when enter button is pressed
		  motor[mR]=100;
       wait1Msec(1000);                   //waits so it doesnt bug up
       motor[mL] = 0;
       motor[mR] = 0;
       wait1Msec(1000);
    }

   ClearMessage();
    }
		}
