#pragma config(Motor,  motorA,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          soulStealer,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*
This is the sender program or the "master" for mohairs robot. It will send messages to the recerver or "slave" program
It sends out messages which is picked up as variables to the other program. We are using two nxt bricks to acomplish this
1 to send out the messages and 1 to reveive the messages and send them out to the motors
*/
task main()
{
	//*NOTE*   0 = Gray Rectangle button.  1 = Right Arrow button.  2 = Left Arrow button.  3 = Orange Square button.
		int theloop = 1;           // defining and setting variablle theloop to 1
		int goes = 1;             // defining and setting variable goes to 2
		bool x = false, y = false;    //creates two boolean variables that is used to indicate if a sound should be played.
		while(theloop==goes)            //just a while loop as long as theloop==goes
		{
			if (nNxtButtonPressed==3)     //If the enter button is pressed it sends a message to the recerve
			{
				sendMessage(3);  // sends 'nMessageID' over an existing Bluetooth Connection
				eraseDisplay ();  //eraces display so messgaes dont overlap
				nxtDisplayString(4, "theloop");  //Displays theloop to make sure it worked and that is the function it is doing
				if(x==true)             //simple if statement for the boolean variables
				{
					y=false;             //if x==true then y== false
				}
				else
			{x = true;}                 //sets x to true
	if(x==true && y == true)       //if statement for both x and y==true
			{
				PlaySound(soundBeepBeep); //if x and y  both ==true them play sound beepbeep
				wait1Msec(1000);            //waits 1 second so program doesnt buug up
			}
				wait1Msec(1000);             //again waits 1 seccond to catch up
			}
			if (nNxtButtonPressed==2)       //if left arrow is pressedd do bellow
			{
				sendMessage(2);               // sends 'nMessageID' over an existing Bluetooth Connection

				eraseDisplay ();             //eraces display so it doesnt overlap messages
				nxtDisplayString(4, "fail");      //displays Fail to show what command it caried out and to make sure it worked
				if(y==true)                     //if y==true
				{
					x = false;                     //if y==true set x=false
				}
				else
			{y = true;}                        //else set y to true
			if(x==true && y == true)          // if both x and y ==true
			{
				PlaySound(soundBeepBeep);       //plays sound beepbeep if both x and y are true
				wait1Msec(1000);                 //waits for 1 second so program doesnt bug up
			}
				wait1Msec(1000);                   //waits for 1 second so program can catch up
			}
			if (nNxtButtonPressed==1)           //if the right button is pressedd do bellow
			{
				sendMessage(1);                     // sends 'nMessageID' over an existing Bluetooth Connection
				eraseDisplay ();                    //eraces display so it doest overlap messages
				nxtDisplayString(4, "hello world");  //displays hello world to show witch function it did and to make sure it worked
				x=y=false;                          //sets x and y to false
				wait1Msec(1000);                     //waits 1 second so program doesnt bug up
			}


		}
}
