#pragma config(Motor,  motorA,          mL,            tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          mR,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mCAT,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
This is a program for mohair's robot.
Mohair's "Bat Mobeile" for the outreach places that we go to.


*/
task main()
{
	/*
	Here just for syntax refrence

	motor[mL]=100;
	motor[mR]=100;
	while (true) {}
	while (nNxtButtonPressed!=kRightButton) {}
	motor[mR]=-100;
	int x=0;

	while (nNxtButtonPressed=kRightButton) {}
	x++;
	(nxtDisplayString(3, "%d", x);

	*/
int x=0;
int xx=0;
eraseDisplay ();
xx = message;
    if (xx==1)//right button
    	{
      x++;                                 //Adds +1 to display everytime right button is pressed
			eraseDisplay () ;
			nxtDisplayString (3, "%d", x);
			motor[mL]=100;                       //robot turns right when right button is pressed
			motor[mR]=-100;
		}

		if (xx==2)//left button
			{
		  x--;                                 //Subtracts -1 to display everytime left button is pressed
			eraseDisplay () ;
			nxtDisplayString (3, "%d", x);
			motor[mL]=-100;                      //robot turns left with left button is pressed
			motor[mR]=100;
		}

		if (xx==3)//center  button
			{
		  motor[mL]=100;                      //robot moves forward when enter button is pressed
		  motor[mR]=100;

		}
		}
