#pragma config(Motor,  motorA,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          soulStealer,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//*NOTE*   0 = Gray Rectangle button.  1 = Right Arrow button.  2 = Left Arrow button.  3 = Orange Square button.
		int weifan = 1;
		int fail = 1;
		bool x = false, y = false;
		while(weifan==fail)
		{
			if (nNxtButtonPressed==3)
			{
				sendMessage(3);  // sends 'nMessageID' over an existing Bluetooth Connection
				nxtDisplayString(4, "weifan");
				if(x==true)
				{
					y=false;
				}
				x = true;
			}
			if (nNxtButtonPressed==2)
			{
				sendMessage(2);  // sends 'nMessageID' over an existing Bluetooth Connection
				nxtDisplayString(4, "fail");
				if(y==true)
				{
					x = false;
				}
				y = true;
			}
			if (nNxtButtonPressed==1)
			{
				sendMessage(1);  // sends 'nMessageID' over an existing Bluetooth Connection
				nxtDisplayString(4, "hello world");
				x=y=false;
			}
			if(x==true && y == true)
			{
				PlaySound(soundBeepBeep);
			}
		}
}
