#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     Lfront,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Lback,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Rfront,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Rback,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     Accessory1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     Accessory2,    tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#define max 100
#define min 0
/*------------------------------------------------|
|Motor A1 is Lfront; Motor A2 is Lback.					  |
|Motor B1 is Rfront; Motor B2 is Rback.						|
|Motor C1 is Accessory;   Motor C2 is Accessory.	|
|Motors run on a scale of -100(max backwards) to  |
|100 (max forwards), with no power being 0.				|
|Servos run on a scale of 0 (max backwards) to 		|
|256(max forwards), with 127 being no power.			|
|------------------------------------------------*/
task main()
{
	waitForStart();
 while(true)
  {
    getJoystickSettings(joystick);  // Update Buttons and Joysticks
    if(joy1Btn(5)==1)
    {
    	motor[Accessory1] = 100;
    	motor[Accessory2] = 100;
    	wait1Msec(100);
    	motor[Accessory1]=0;
  		motor[Accessory2]=0;
    }
    if(joy1Btn(6)==1)
    {
    	motor[Accessory1] = -100;
    	motor[Accessory2] = -100;
    	wait1Msec(100);
    	motor[Accessory1]=0;
  		motor[Accessory2]=0;
    }
	if(abs(joystick.joy1_y1)>10)
	{
		motor[LFront] = joystick.joy1_y1;
		motor[LBack] = joystick.joy1_y1;
	}
	else
	{
		motor[Rfront] = 0;
		motor[Rback] = 0;
	}
	if(abs(joystick.joy1_y2)>10)
	{
		motor[Rfront] = joystick.joy1_y2;
		motor[Rback] = joystick.joy1_y2;
	}
	else
	{
		motor[Rfront] = 0;
		motor[Rback] = 0;
	}
 }
}
