#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S3, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     IR,             sensorHiTechnicIRSeeker600)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     Right1,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Right2,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C1_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_1,     Left1,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_2,     Left2,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#define max 100
#define min 0
/*------------------------------------------------|
|Motor A1 is Lfront; Motor A2 is Lback.					  |
|Motor C1 is Rfront; Motor C2 is Rback.						|
|Motor B1 is Accessory;   Motor B2 is Accessory.	|
|Motors run on a scale of -100(max backwards) to  |
|100 (max forwards), with no power being 0.				|
|Servos run on a scale of 0 (max backwards) to 		|
|256(max forwards), with 127 being no power.			|
|------------------------------------------------*/
task main()
{
	waitForStart();
 while(true)
  {
    getJoystickSettings(joystick);  // Update Buttons and Joysticks
		if(abs(joystick.joy1_y1)>10)
		{
			motor[Left1] = (joystick.joy1_y1*100)/128;
			motor[Left2] = (joystick.joy1_y1*100)/128;
		}
		else
		{
			motor[Left1] = 0;
			motor[Left2] = 0;
		}

		if(abs(joystick.joy1_y2)>10)
		{
			motor[Right1] = (joystick.joy1_y2*100)/128;
			motor[Right2] = (joystick.joy1_y2*100)/128;
		}
		else
		{
			motor[Right1] = 0;
			motor[Right2] = 0;
		}
 	}
}
