#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     mLeft,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mRight,        tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#define max 100
#define min 0
#define right 1
#define left -1
/*------------------------------------------------|
|Motor A1 is Lfront; Motor A2 is Lback.					  |
|Motor B1 is Rfront; Motor B2 is Rback.						|
|Motor C1 is Accessory;   Motor C2 is Accessory.	|
|Motors run on a scale of -100(max backwards) to  |
|100 (max forwards), with no power being 0.				|
|Servos run on a scale of 0 (max backwards) to 		|
|256(max forwards), with 127 being no power.			|
|------------------------------------------------*/

void initializeRobot()
{
  return;
}

task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.
	//let's start dat autonomous let's gooooooooooooooooo
  motor[Lfront] = 100;
  motor[Lback] = 100;
  motor[Rfront] = 100;
  motor[Rback] = 100;
  wait10Msec(100);

  motor[Lfront] = -100;
  motor[Lback] = -100;
  motor[Rfront] = 100;
  motor[Rback] = 100;
  wait1Msec(500);

  motor[Lfront] = 100;
  motor[Lback] = 100;
  motor[Rfront] = 100;
  motor[Rback] = 100;
  wait10Msec(100);

  while (true) //teleOp start let's gooooooooooooooooo
  {
    if (bDisconnected)
    {
    	motor[Lback] = 0;
    	motor[Lfront] = 0;
    	motor[Rback] = 0;
    	motor[Rfront] = 0;
    }

		getJoystickSettings(joystick);  // Update Buttons and Joysticks
    if(joy1Btn(5)==1)
    {
    	motor[Accessory1] = 100;
    	motor[Accessory2] = 100;
    	wait1Msec(100);
    	motor[Accessory1]=0;
  		motor[Accessory2]=0;
    }
    if(joy1Btn(6)==1)
    {
    	motor[Accessory1] = -100;
    	motor[Accessory2] = -100;
    	wait1Msec(100);
    	motor[Accessory1]=0;
  		motor[Accessory2]=0;
    }
  	if (joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10)
  	{
  		motor[Lfront]= 0;
  		motor[Lback] = 0;
  	}
  	else if (joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10)
  	{
  		motor[Rfront]= 0;
  		motor[Rback] = 0;
  	}
  	else
  	{
			motor[Lfront] = joystick.joy1_y1;  //left-back   // MotorA1's powerlevel is set to the y1 stick's current position.
  		motor[Lback] = joystick.joy1_y1;	 //left-front  // MotorA2's powerlevel is set to the y1 stick's current position.
  		motor[Rfront] = joystick.joy1_y2;	 //right-back	 // MotorB1's powerlevel is set to the y2 stick's current position.
  		motor[Rback] = joystick.joy1_y2;	 //right-front // MotorB2's powerlevel is set to the y2 stick's current position.
		}
  }
}
