#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     mWinch,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     mWinchier,     tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{while (true){
motor[mWinch] = 100;
motor[mWinchier] = 100;
wait10Msec(60000);
motor[mWinch] = motor[mWinchier] = 0;

}

}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      bvf
