#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Ultra,          sensorSONAR)
#pragma config(Sensor, S3,     Ultra2,         sensorSONAR)
#pragma config(Sensor, S4,     IR,             sensorHiTechnicIRSeeker600)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     mLift2,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     mRight,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     mLift1,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     mFlag,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     mLeft,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     mWrist,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    AutoHook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    sHook,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* FOR ROHIT TO FIX
* 1:
* 2:
* 3:
* 4:
*/

/******************************
* DISTANCES TO EACH BOX	      *
* To box 2(forward) 3872      *
* To box 3(forward) 6657      *
* To box 2(backward) -2012    *
* To box 3(backward)  -4980   *
* To box 4(forward) 7641      *
* To box 4(backward) -6301    *
******************************/

#define left 1
#define right -1

// whether the user has finished selecting a delay time
bool timeSelected = false;
// whether the robot will wait for the FCS to start (disable when testing)
bool startSelected = false;
// whether the user has selected to delay at the beginning of autonomous
bool waitSelected = true;
// how many seconds to delay before starting autonomous (used for coordinating with
// other teams)
int waitTime = 0;
// the message used by the wait prompt
string wait = "Yes";
//holds which  autonomous program we will be running
int programCounter = 1;
//holds the  maximum amount of autonomous programs we can run
int max = 6;

// standard library for talking to Samantha FCS
#include "JoystickDriver.c"
// our team-built function library
#include "FunctionLibrary.c"
//our team-built Autonomous library
#include "SmoothAutoLibrary.c"

task main()
{
	servo[sHook] = 0;
	servo[AutoHook] = 230;
	 selectTime();
	 startSelect();
	 while(true)
	 {
	   counter();
	  if(programCounter == 1)
		{
	    nxtDisplayCenteredTextLine(2, "Regular Autonomous");
	    if(nNxtButtonPressed == 3)
	    {
	        PlaySound(soundBlip);
	        if(waitSelected){waitForStart();}
	        wait1Msec(waitTime*1000);

	        AutoNoStop_F();

	        wait1Msec(500);
	    }
	  }
	  else if(programCounter == 2)
	  {
	    nxtDisplayCenteredTextLine(2, "FA to FR");
	    if(nNxtButtonPressed == 3)
	    {
	        PlaySound(soundBlip);
	        if(waitSelected){waitForStart();}
	        wait1Msec(waitTime*1000);

	        AutoNSF_Front();

	        wait1Msec(500);
	    }
	  }
	  else if(programCounter == 3)
	  {
	    nxtDisplayCenteredTextLine(2, "FA to BR");
	    if(nNxtButtonPressed == 3)
	    {
	        PlaySound(soundBlip);
	        if(waitSelected){waitForStart();}
	        wait1Msec(waitTime*1000);

	        AutoNSF_Back();

	        wait1Msec(500);
	    }
	  }
	  else if(programCounter == 4)
	  {
	    nxtDisplayCenteredTextLine(2, "Backwards Autonomous");
	    if(nNxtButtonPressed == 3)
	    {
	        PlaySound(soundBlip);
	         if(waitSelected){waitForStart();}
	        wait1Msec(waitTime*1000);

	        AutoNoStop_B();

	        wait1Msec(500);
	    }
	  }
	  else if(programCounter  == 5)
	  {
	  	nxtDisplayCenteredTextLine(2, "BA to FR");
	  	if(nNxtButtonPressed == 3)
	  	{
	  		PlaySound(soundBlip);
	  		if(waitSelected){waitForStart();}
	  		wait1Msec(waitTime * 1000);

	  		AutoNSB_Front();

	  		wait1Msec(500);
	  	}
	  }
	  else if(programCounter == 6)
	  {
	    nxtDisplayCenteredTextLine(2, "BA to BR");
	    if(nNxtButtonPressed == 3)
	    {
	        PlaySound(soundBlip);
	        if(waitSelected){waitForStart();}
	        wait1Msec(waitTime*1000);

	        AutoNSB_Back();

	        wait1Msec(500);
	    }
	  }
	}
}
