#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	nMotorEncoder[motorD] = 0;
	while(true)
	{
		motor[motorE] =100;
		int k = nMotorEncoder[motorD];
		nxtDisplayCenteredTextLine(4, "%d", k);
	}
}
