#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     Ultra,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     A,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     B,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     C,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     D,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     E,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     F,             tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,                tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int wfn = 0;
	bool yolo = true;
	while(yolo)
	{
		wfn = SensorValue[Ultra];
		if(wfn>=255 || wfn<0)
		{
			nxtDisplayTextLine(5,"y u do dis");
			wait1Msec(1000);
			eraseDisplay();
			wait1Msec(10);
		}
		else
		{
			nxtDisplayTextLine(5,"I can see dat");
			wait1Msec(1000);
			eraseDisplay();
			wait1Msec(10);
		}
	}



}
